services:
  server-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - SERVERS=raft-server-2:1234,raft-server-3:1234,raft-server-4:1234,raft-server-5:1234
    container_name: raft-server-1
    networks:
      - raft-network
    volumes:
      - raft-1:/root/data
  server-2:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - SERVERS=raft-server-1:1234,raft-server-3:1234,raft-server-4:1234,raft-server-5:1234
    depends_on:
      - server-1
    container_name: raft-server-2
    networks:
      - raft-network
    volumes:
      - raft-2:/root/data
  server-3:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - SERVERS=raft-server-1:1234,raft-server-2:1234,raft-server-4:1234,raft-server-5:1234
    depends_on:
      - server-1
    container_name: raft-server-3
    networks:
      - raft-network
    volumes:
      - raft-3:/root/data
  server-4:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - SERVERS=raft-server-1:1234,raft-server-2:1234,raft-server-3:1234,raft-server-5:1234
    depends_on:
      - server-1
    container_name: raft-server-4
    networks:
      - raft-network
    volumes:
      - raft-4:/root/data
  server-5:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - SERVERS=raft-server-1:1234,raft-server-2:1234,raft-server-3:1234,raft-server-4:1234
    depends_on:
      - server-1
    container_name: raft-server-5
    networks:
      - raft-network
    volumes:
      - raft-5:/root/data
volumes:
  raft-1:
  raft-2:
  raft-3:
  raft-4:
  raft-5:

networks:
  raft-network: