services:
  etcd-1:
    image: quay.io/coreos/etcd:v3.5.0
    command: [ "etcd", "--data-dir=/etcd-data", "--log-level=error"]
    volumes:
      - etcd-1:/etcd-data
    container_name: raft-etcd-1
  etcd-2:
    image: quay.io/coreos/etcd:v3.5.0
    command: [ "etcd", "--data-dir=/etcd-data", "--log-level=error"]
    volumes:
      - etcd-2:/etcd-data
    container_name: raft-etcd-2
  etcd-3:
    image: quay.io/coreos/etcd:v3.5.0
    command: [ "etcd", "--data-dir=/etcd-data", "--log-level=error"]
    volumes:
      - etcd-3:/etcd-data
    container_name: raft-etcd-3
  etcd-4:
    image: quay.io/coreos/etcd:v3.5.0
    command: [ "etcd", "--data-dir=/etcd-data", "--log-level=error"]
    volumes:
      - etcd-4:/etcd-data
    container_name: raft-etcd-4
  etcd-5:
    image: quay.io/coreos/etcd:v3.5.0
    command: [ "etcd", "--data-dir=/etcd-data", "--log-level=error"]
    volumes:
      - etcd-5:/etcd-data
    container_name: raft-etcd-5

  server-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - ETCD_ENDPOINT=http://etcd-1:2379
    depends_on:
      - etcd-1
    container_name: raft-server-1

  server-2:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - ETCD_ENDPOINT=http://etcd-2:2379
    depends_on:
      - etcd-2
      - server-1
    container_name: raft-server-2

  server-3:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - ETCD_ENDPOINT=http://etcd-3:2379
    depends_on:
      - etcd-3
      - server-1
    container_name: raft-server-3

  server-4:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - ETCD_ENDPOINT=http://etcd-4:2379
    depends_on:
      - etcd-4
      - server-1
    container_name: raft-server-4

  server-5:
    image: raft:latest
    environment:
      - ELECTION_TIMEOUT=1s
      - ETCD_ENDPOINT=http://etcd-5:2379
    depends_on:
      - etcd-5
      - server-1
    container_name: raft-server-5

volumes:
  etcd-1:
  etcd-2:
  etcd-3:
  etcd-4:
  etcd-5: